### ISSUE TITLE
Choose buckets

### ISSUE THREAD

**Issue by thalescm** [TestArmada/flank#31]
Why is it necessary to upload the apks to a gs bucket instead of using the ones on the provided path directly?

Another thing, are there plans to support other kind of buckets? My current CI saves the apks on a s3 bucket on aws, it would be nice to fetch than from there and not needing to replicate them to gs://<>

The last thing, is there a `CONTRIBUTING.md` guide somewhere or is just to fork and make a PR with the desired feature?

**Comment by bootstraponline** [comment]
> Why is it necessary to upload the apks to a gs bucket instead of using the ones on the provided path directly?

It's expensive in terms of time if we use the apks from the local file system. Every shard would have to upload the test and app apk again. This also introduces flakiness since each additional network request is another chance for failure.

---

> Another thing, are there plans to support other kind of buckets?

Bucket support is limited to what Google's gcloud CLI tool allows.

> The path to the application binary file. The path may be in the local filesystem or in Google Cloud Storage using gs:// notation.
>
> https://cloud.google.com/sdk/gcloud/reference/beta/test/android/run

---

> The last thing, is there a CONTRIBUTING.md guide somewhere

We should add a contributing guide. It's probably better to open an issue first for any desired features before submitting a PR. Otherwise you may add a feature that isn't a good fit for the project (for example decreasing performance and stability by uploading the apks every time).

**Comment by bootstraponline** [comment]
Also make sure you are using master since the apk uploading logic has changed. We're now matching the gcloud CLI behavior in terms of storage paths.

**Comment by thalescm** [comment]
Ok, thanks for the answers, I'll open an issue with the desired feature!
