### ISSUE TITLE
Sravan | Always find xctestrun file - avoid hard coding file name

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#336]
search for `$DD/Build/Products/*.xctestrun` or similar instead of requiring a hard coded path that changes as new iOS versions are released

Support environment variables and tilda as well

we should enable auto discovery by default

---

Also support wildcard for APK discovery. Look into supporting `~` expansion as well.

**Comment by sravanmedarapu** [comment]
Acceptance Criteria:
`app`, `test` and `xctestrun-file` values in Flank config should support below formats along with current formats.
1) tilda expansion
2) environment variable expansion
3) globbing with `*` and `**`
Ex: 
```
app: ~/repo/app-*.apk
test: $DERIVED_DATA/**/*. xctestrun
```

**Comment by sravanmedarapu** [comment]
**Findings:**
The initial thought was to check java inbuilt support but turns out not. Below is the current findings
1) tilda expansion->  there is no inbuilt support, might need to rely on `System.getProperty("user.home")`

2) environment variable expansions -> no inbuilt support, might end up relying on the regular expression for filtering the environment variables `\$([a-zA-Z_]{1,}[a-zA-Z0-9_]{0,})`
 

3) glob support with `*` & `**`  -> java has inbuilt support, we just need to figure out the base path and blog path, again might end up using regex for `([^*]*/)`.
http://java.boot.by/ocpjp7-upgrade/ch06s05.html

```
Ex:
        String glob = "glob:**/app*.apk";
        String path = System.getProperty("user.home");
        final PathMatcher pathMatcher = FileSystems.getDefault().getPathMatcher(
                glob);

        Files.walkFileTree(Paths.get(location), new SimpleFileVisitor<Path>() {

            @Override
            public FileVisitResult visitFile(Path path,
                                             BasicFileAttributes attrs) throws IOException {
                if (pathMatcher.matches(path)) {
                    System.out.println(path);
                }
                return FileVisitResult.CONTINUE;
            }

            @Override
            public FileVisitResult visitFileFailed(Path file, IOException exc)
                    throws IOException {
                return FileVisitResult.CONTINUE;
            }
        });
```
