### ISSUE TITLE
Optionally upload results/ to GCS 

### ISSUE THREAD

**Issue by rpappalax** [TestArmada/flank#339]
The test results (reports) are a great feature but we typically run our tests in a remote, secure CI system.  Ideally, there would also be an option to automatically upload them to the GCP bucket when the test was completed like the (apks and shard data).

**Comment by bootstraponline** [comment]
That's a great request. I agree this makes sense.

**Comment by rpappalax** [comment]
i notice that test reports are only made available when async: false, which I guess makes sense.
I'd prefer to use async: true, but I wonder if this feature were made available, would it still be possible to  publish the results to the storage bucket?  or are these results only tallied locally when async: false?

**Comment by bootstraponline** [comment]
> i notice that test reports are only made available when async: false, which I guess makes sense.
> I'd prefer to use async: true, but I wonder if this feature were made available, would it still be possible to publish the results to the storage bucket? or are these results only tallied locally when async: false?

to get reports from `async: true`, use the `refresh` command.

the reports are generated from the `matrix_ids.json` in the `results/` folder.

I'm not sure what report uploading would look like in an async workflow, we may have to chat a bit on slack.

**Comment by bootstraponline** [comment]
@rpappalax Is there any reason gcloud CLI can't be used to upload the files to the desired bucket?

**Comment by bootstraponline** [comment]
I added `--results-dir` support so that it's easy to use known folder paths for results. The results can then be uploaded to Google Storage/Amazon S3/etc. per user needs.

After talking with the team, baking in support for auto uploading to GCS is a less flexible solution than having users upload the files. In general the reporting artifacts should be attached to builds as artifacts in Bitrise/Jenkins. When that's not possible, a user supplied shell script can upload the reports to wherever is required.

In the future once Flank has an API, it'll be easier to customize the behavior without having to land the functionality into the core project.
