### ISSUE TITLE
Missing full tests results

### ISSUE THREAD

**Issue by geaden** [TestArmada/flank#76]
Due to changes in naming convention on FTL side, after fetching results there is only one file `test_results_0.xml` and it corresponds to tests executed on the last shard. The same is also applied to `coverage.ec`.

**Comment by bootstraponline** [comment]
may be fixed by https://github.com/TestArmada/flank/pull/75

**Comment by rciovati** [comment]
@bootstraponline That PR doesn't aim to solve this particular issue and unfortunately after the execution the local `results` folder will contain just one `test_results_0.xml` file. It's possible to get all the report files in the `bucket` folder though. We are considering to create an additional PR to rename the result files to have the shard index as well.

**Comment by bootstraponline** [comment]
Oh, interesting. I think an additional PR may make sense.

**Comment by jwgcarlson** [comment]
I'm not all too familiar with Flank, but it looks like GsutilTool is currently pulling down the XML result files with a command like this:

    gsutil -m cp -r -U $bucket/**.xml $dest

I recommend using `gsutil rsync` instead, to preserve the directory structure of the GCS bucket. Here's a command to grab only the `test_result_*.xml` files:

    gsutil -m rsync -n -r -x '^((?!test_result_\d+\.xml).)*$' $bucket $dest

Then, rather than scanning the stderr of the `gsutil` command to get the filenames (which is what I think `GsutilTool.getDeviceNames()` is doing), you can just inspect the local `$dest` directory.

**Comment by renas** [comment]
Thanks @jwgcarlson. Works great.
