### ISSUE TITLE
Specify or calculate default test time.

### ISSUE THREAD

**Issue by runningcode** [TestArmada/flank#82]
Right now it's a bit of a pain to have to update the flank.tests every time a new test is added. If new tests would automatically be added to other shards based on an average test duration time, or a default value specified in config.properties, it would save a bit of time having to update the test times every time a new test is added.

**Comment by renas** [comment]
@runningcode How do you mean you need to update the flank.tests every time a new test is added? When a new test is introduced its executed in isolation so that Flank can save the tests execution time in flank.tests. Next time you run the test suite and the test is found in flank.tests, it will know how to package it and will put it in a shard. This should all be automatic.

**Comment by runningcode** [comment]
I mean: the can the test be introduced to another shard and then timed from there instead of running by itself?

**Comment by renas** [comment]
We'll look into this. Thanks for the suggestion.

**Comment by runningcode** [comment]
On the same note, if a test becomes 2x longer, it seems that the test duration isn't updated by itself. Is there a way to do that without removing it from flank.tests?

**Comment by bootstraponline** [comment]
Hi, thanks for opening an issue on the Flank repo. The Kotlin rewrite is now available for testing and feedback. This replaces the Java version of Flank.

- https://github.com/TestArmada/flank/releases/tag/flank_snapshot

Join us in the`#flank` channel on the Firebase slack to chat. If this is still an issue in the new release, comment and let me know.

-  https://firebase.community/
